version: '3.9'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "user-signup-topic,file-upload,authentication"
  email-service:
    build: ./email-service
    ports:
      - "8051:8051"
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  file-upload-service:
    build: ./fileserver-service
    ports:
      - "8050:8050"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  authentication-service:
    build: ./user-auth-service
    ports:
      - "8055:8055"
    depends_on:
      - redis
      - kafka
      - db
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: { }